
export const PLANETS = Object.freeze([ 
    "Corellia",
    "Rodia",
    "Nal Hutta",
    "Dantooine",
    "Bestine IV",
    "Ord Mantell",
    "Trandosha",
    "Socorro",
    "Geonosis",
    "Utapau",
    "Mustafar",
    "Kashyyyk",
    "Polis Massa",
    "Mygeeto",
    "Felucia",
    "Cato Neimoidia",
    "Saleucami",
    "Stewjon",
    "Mon Cala",
    "Chandrila",
    "Sullust",
    "Toydaria",
    "Malastare",
    "Dathomir",
    "Ryloth",
    "Aleen Minor",
    "Vulpter",
    "Troiken",
    "Tund",
    "Haruun Kal",
    "Cerea",
    "Glee Anselm",
    "Iridonia",
    "Tholoth",
    "Iktotch",
    "Quermia",
    "Dorin",
    "Champala",
    "Mirial",
    "Serenno",
    "Concord Dawn",
    "Zolan",
    "Ojom",
    "Skako",
    "Muunilinst",
    "Shili",
    "Kalee",
    "Umbara",
    "Jakku",
    "Tatooine",
    "Alderaan",
    "Yavin IV",
    "Hoth",
    "Dagobah",
    "Bespin",
    "Endor",
    "Naboo",
    "Coruscant",
    "Kamino" 
]);