export const SPECIES = Object.freeze([
    "Neimodian",
    "Gungan",
    "Toydarian",
    "Dug",
    "Twi'lek",
    "Aleena",
    "Vulptereen",
    "Xexto",
    "Toong",
    "Cerean",
    "Nautolan",
    "Zabrak",
    "Tholothian",
    "Iktotchi",
    "Quermian",
    "Kel Dor",
    "Chagrian",
    "Geonosian",
    "Mirialan",
    "Clawdite",
    "Besalisk",
    "Kaminoan",
    "Skakoan",
    "Muun",
    "Togruta",
    "Kaleesh",
    "Pau'an",
    "Human",
    "Droid",
    "Wookiee",
    "Rodian",
    "Hutt",
    "Yoda's species",
    "Trandoshan",
    "Mon Calamari",
    "Ewok"
]);
